NexenHub/Controllers/LotController.cs
using Microsoft.AspNetCore.Mvc;
using NexenHub.Models;
using NexenHub.Pages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace NexenHub.Controllers
{

    [Route("api/[controller]")]
    [ApiController]
    public class LotController : ControllerBase
    {
        [HttpGet("lothis/{lotid}")]
        public ActionResult<List<LotHisItem>> Get(string lotid)
        {
            if (lotid.Length == 15)
            {
                LotItem lot = new LotItem(lotid);
                lot.LoadHistory();
                lot.RemoveUselessHistory();

                return lot.History;
            }
            else
            {
                return BadRequest();
            }
        }

        [HttpGet("topdf")]
        public ActionResult ConvertToPDF()
        {
            return null;
        }



    }
}

NexenHub/Controllers/RexController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NexenHub.Class;
using NexenHub.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NexenHub.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class RexController : ControllerBase
    {
        GlobalDatabase dbglob = new GlobalDatabase();

        [HttpGet("version")]
        public ActionResult<RexVersion> GetVersion()
        {
            RexVersion rexver = new RexVersion();
            return rexver;
        }

        [HttpGet("latestversion")]
        public ActionResult<DateTime> GetLatestVersion()
        {
            AppVersionRex version = new AppVersionRex();
            return version.VersionDate;
        }

        // TODO: Can be deleted if every rex is > 22-11-30
        [HttpPost("reportversion")]
        public ActionResult PostReportVersion()
        {
            try 
            { 
                HttpRequest request = HttpContext.Request;

                string ip = request.Headers.ContainsKey("ip") ? request.Headers["ip"].ToString() : "";
                string versionName = request.Headers.ContainsKey("versionName") ? request.Headers["versionName"].ToString() : "";
                string appId = request.Headers.ContainsKey("appId") ? request.Headers["appId"].ToString() : "";

                dbglob.UpdateVersion(appId, ip, versionName);

            }
            catch
            {
                return BadRequest();
            }

            return Ok();
        }


        [HttpPost("reportSoftware")]
        public ActionResult PostReportSoftware()
        {
            try
            {
                var httpRequest = HttpContext.Request;

                string ip = httpRequest.Form["ip"].ToString();
                string versionName = httpRequest.Form["versionName"].ToString();
                string appId = httpRequest.Form["appId"].ToString();

                dbglob.UpdateVersion(appId, ip, versionName);

            }
            catch
            {
                return StatusCode(StatusCodes.Status500InternalServerError);
            }

            return Ok();
        }

        [HttpGet("lotitem/{code}")]
        public ActionResult<LotItem> GetLotItem(string code)
        {
            string lotid = "";

            if (code.Length == 5)
                lotid = dbglob.Cart2Lot(code);
            else if (code.Length == 15)
                lotid = code;

            if (lotid.Length == 15)
            {
                LotItem lot = new LotItem(lotid);
                lot.LoadHistoryClean();
                lot.RemoveUselessHistory();

                return lot;
            }
            else
            {
                return BadRequest();
            }
        }


        [HttpGet("commongt/{lotid}")]
        public ActionResult<List<string>> GetCommonGt(string lotid)
        {
            return dbglob.GetCommonGt(lotid);
        }


    }
}

NexenHub/Pages/BestOnes.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NexenHub.Pages
{
    public class BestOnesModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

NexenHub/Pages/Dashboard/Status.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NexenHub.Class;

namespace NexenHub.Pages.Dashboard
{

    public class StatusModel : PageModel
    {

        GlobalDatabase dbglob = new GlobalDatabase();
        public List<StatusEq> statuses;


        public void OnGet(string proc)
        {
            DataTable dt = dbglob.GetDashboardStatus(proc);
            
            statuses = new List<StatusEq>();

            foreach (DataRow row in dt.Rows)
            {
                StatusEq eq = new StatusEq();
                eq.ID = row["EQ_ID"].ToString();
                eq.Name = row["EQ_NAME"].ToString();
                eq.Downtime = row["NON_NAME"].ToString();
                eq.Item_id = row["ITEM_ID"].ToString();
                //eq.BgColor = row["BGCOLOR"].ToString();
                //eq.FrColor = row["FRCOLOR"].ToString();
                statuses.Add(eq);
            }
        }
    }
}

NexenHub/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace NexenHub.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

NexenHub/Pages/Forbidden.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NexenHub.Pages
{
    public class ForbiddenModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

NexenHub/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using NexenHub.ViewModels;

namespace NexenHub.Pages
{
    public class IndexModel : PageModel
    {

        public YearProd yearProd;

        public void OnGet()
        {
            yearProd = new YearProd();
        }

        
    }
}

NexenHub/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NexenHub.Class;

namespace NexenHub.Pages
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public string Username { get; set; }
        [BindProperty]
        public string Password { get; set; }

        [BindProperty]
        public string ErrorMsg { get; set; }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostLogin()
        {           
            bool logged = await Login.LogIn(HttpContext, Username, Password);

            if (logged) 
            { 
                return LocalRedirect("/index");
            }
            else
            {
                ErrorMsg = "Unable to login";
                return Page();
            }
        }
    }
}

NexenHub/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NexenHub.Class;
using System.Threading.Tasks;

namespace NexenHub.Pages
{
    public class LogoutModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string returnPath { get; set; }

        public async Task<IActionResult> OnGet()
        {

            await Login.Logout(HttpContext);

            if (string.IsNullOrEmpty(returnPath))
                return LocalRedirect("/index");
            else
                return LocalRedirect(returnPath);

        }
    }
}

NexenHub/Pages/Lot.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NexenHub.Models;
using NexenHub.Class;
using NetBarcode;
using System.Data;
using System.Net;

namespace NexenHub.Pages
{
    public class LotModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string arglot { get; set; }
        public LotItem lotitem { get; set; }
        public Barcode lotBarcode { get; set; }
        public string ip { get; set; }
        public List<LotItem> Parents { get; set; }

        private GlobalDatabase dbglob = new GlobalDatabase();

       // public bool FuckHim { get; set; }

        public void OnGet()
        {
            //Random rnd = new Random();
            //string clientIP = "";
            //string header = (HttpContext.Request.Headers["CF-Connecting-IP"].FirstOrDefault() ?? HttpContext.Request.Headers["X-Forwarded-For"].FirstOrDefault());
            //if (IPAddress.TryParse(header, out IPAddress ip)) {
            //    clientIP = ip.ToString();
            //    FuckHim = (clientIP == "172.15.9.70" || clientIP == "172.15.9.73"); // && rnd.Next(3) <= 1;
            //}


            if (arglot.Length == 5)
                arglot = dbglob.Cart2Lot(arglot);

            lotitem = new LotItem(arglot);
            lotitem.LoadHistory();
            lotitem.RemoveUselessHistory();

            lotBarcode = new Barcode(lotitem.LOT_ID, NetBarcode.Type.Code128B) ;

            TraceLot();
        }

        private void TraceLot()
        {
            Parents = new List<LotItem>();
            foreach (DataRow row in dbglob.GetLotParents(lotitem.LOT_ID).Rows)
                Parents.Add(new LotItem(row["INPUT_LOT_ID"].ToString()));
        }
    }
}

NexenHub/Pages/MachineList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NexenHub.Class;

namespace NexenHub.Pages
{
    public class MachineListModel : PageModel
    {
        public List<String> Procs => DbList.GroupBy(x => x.WC_ID).Select(f=>f.Key).ToList();

        public List<MachineListObject> DbList;

        private GlobalDatabase dbglobal = new GlobalDatabase();


        public void OnGet()
        {
            CreateList();
        }

        private void CreateList()
        {
            DataTable dt = dbglobal.GetMachineList(); ;
            DbList = new List<MachineListObject>();
            foreach (DataRow r in dt.Rows)
            {
                if (!GlobalSettings.IgnoredMachines.Contains(r["EQ_ID"].ToString()))
                    DbList.Add(new MachineListObject
                    {
                        EQ_ID = r["EQ_ID"].ToString(),
                        FACT_ID = r["FACT_ID"].ToString(),
                        Name = r["Name"].ToString(),
                        WC_ID = r["WC_ID"].ToString(),
                        PROC_ID = r["PROC_ID"].ToString()
                    });
            }
        }

    }
}

NexenHub/Pages/MachineReport.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NexenHub.Class;
using NexenHub.Models;

namespace NexenHub.Pages
{
    public class MachineReportModel : PageModel
    {

        #region URL arguments

        [BindProperty(SupportsGet =true)]
        public string eqArg { get; set; }

        [BindProperty(SupportsGet = true)]
        public DateTime startArg { get; set; }

        [BindProperty(SupportsGet = true)]
        public DateTime endArg { get; set; }

        #endregion

        #region GUI variables

        [BindProperty]
        public string SelectedMachine { get; set; }

        [BindProperty]
        public string DateFrom { get; set; }

        [BindProperty]
        public string DateTo { get; set; }

        public bool IsValid { get; set; }

        public List<MachineListObject> Machines;

        #endregion

        public MachineQuality qualityData;

        public MachineProdReport reportData;

        public MachineUsedMat reportUsedMaterial;

        private GlobalDatabase dbglobal = new GlobalDatabase();

        public void OnGet()
        {
            CreateMachineList();
            if (eqArg != null && Machines.Find(m => m.EQ_ID == eqArg) != null)
                SelectedMachine = eqArg;

            if (startArg != null && startArg != DateTime.MinValue)
                DateFrom = startArg.ToString("yyyy-MM-dd");
            else
                DateFrom = DateTime.Now.ToString("yyyy-MM-dd");

            if (endArg != null && endArg != DateTime.MinValue)
                DateTo = endArg.ToString("yyyy-MM-dd");
            else
                DateTo = DateFrom;
            //DateTo = DateTime.Now.ToString("yyyy-MM-dd");

            if (!string.IsNullOrEmpty(SelectedMachine))
                Generate();

        }

        public void OnPostGenerate()
        {
            CreateMachineList();
            Generate();
        }

        private void Generate()
        {
            IsValid = ValidateInput(); 
        }

        private Boolean ValidateInput()
        {
            DateTime genFrom;
            DateTime genTo;

            if (!string.IsNullOrEmpty(SelectedMachine) && 
                !string.IsNullOrEmpty(DateFrom) && DateTime.TryParse(DateFrom, out genFrom) &&
                !string.IsNullOrEmpty(DateTo) && DateTime.TryParse(DateTo,out genTo))
            {
                qualityData = new MachineQuality(SelectedMachine, genFrom, genTo);
                reportData = new MachineProdReport(SelectedMachine, genFrom, genTo);
                reportUsedMaterial = new MachineUsedMat(SelectedMachine, genFrom, genTo);
                //reportDowntTimes = new MachineDownTime(SelectedMachine, genFrom, genTo);
                return true;
            }

            return false;
        }

        private void CreateMachineList()
        {
            DataTable dt = dbglobal.GetMachineList(); ;
            Machines = new List<MachineListObject>();
            foreach (DataRow r in dt.Rows)
            {
                if (!GlobalSettings.IgnoredMachines.Contains(r["EQ_ID"].ToString()) && r["WC_ID"].ToString() != "U")
                    Machines.Add(new MachineListObject
                    {
                        EQ_ID = r["EQ_ID"].ToString(),
                        Name = r["Name"].ToString(),
                        WC_ID = r["WC_ID"].ToString(),
                        PROC_ID = r["PROC_ID"].ToString()
                    });
            }
        }
    }
}

NexenHub/Pages/Rex.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NexenHub.Class;
using NexenHub.Models;

namespace NexenHub.Pages
{
    public class RexModel : PageModel
    {             
        //public RexVersion version = new RexVersion();

        public AppVersionRex RexVer = new AppVersionRex();

        public void OnGet()
        {

        }

        public ActionResult OnGetDownload()
        {
            return File(RexVer.filePath, RexVer.contentType, RexVer.fileName);   
        }
    }
}

NexenHub/Pages/Status.cshtml.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NexenHub.Class;

namespace NexenHub.Pages
{

    public class StatusModel : PageModel
    {

        GlobalDatabase dbglob = new GlobalDatabase();
        public List<StatusEq> statuses;


        public void OnGet(string proc)
        {
            DataTable dt = dbglob.GetDashboardStatus(proc);
            
            statuses = new List<StatusEq>();

            foreach (DataRow row in dt.Rows)
            {
                StatusEq eq = new StatusEq();
                eq.ID = row["EQ_ID"].ToString();
                eq.Name = row["EQ_NAME"].ToString();
                eq.Downtime = row["NON_NAME"].ToString();
                eq.Item_id = row["ITEM_ID"].ToString();
                //eq.BgColor = row["BGCOLOR"].ToString();
                //eq.FrColor = row["FRCOLOR"].ToString();
                statuses.Add(eq);
            }
        }
    }
}

NexenHub/Pages/Tire.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NetBarcode;
using NexenHub.Class;
using NexenHub.Models;

namespace NexenHub.Pages
{
    public class TireModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string argBarcode { get; set; }
        public Tire tire { get; set; }
        public Barcode tireBarcode { get; set; }
        public bool showBarcode { get; set; }

        public string imageTireLogo { get => GlobalSettings.ImageTireLogo(tire.TireItem.PATTERN); }

        public void OnGet()
        {
            tire = new Tire(argBarcode);

            if (!string.IsNullOrEmpty(tire.Barcode)) 
            { 
                tireBarcode = new Barcode(tire.Barcode, NetBarcode.Type.Code128B);
                showBarcode = true;
            }
        }
    }
}

NexenHub/Pages/BestOnes.cshtml
@page
@model NexenHub.Pages.BestOnesModel
@{
    ViewData["Title"] = "Best ones";
}
@*
<div class="">

    <figure class="text-center">
        <blockquote class="blockquote">
            <p>In past, we make it</p>
        </blockquote>
        <figcaption class="blockquote-footer">
            Petr Klíma, <cite title="Source Title">2021</cite>
        </figcaption>
    </figure>

    <figure class="text-center">
        <blockquote class="blockquote">
            <p>
                I wish all of our team members a good holiday during the shutdown period.<br />
                Team members who are working during this period, please suffer.
            </p>
        </blockquote>

        <figcaption class="blockquote-footer">
            Lucas, <cite title="Source Title">2021</cite>
        </figcaption>
    </figure>

    <figure class="text-center">
        <blockquote class="blockquote">
            <p>
                I've never doubted your work skills or skills. <br />
                But I've never expected you to be loyal to the company or to be loyal to the company.
            </p>
        </blockquote>
        <figcaption class="blockquote-footer">
            Lucas, <cite title="Source Title">2021</cite>
        </figcaption>
    </figure>

    <figure class="text-center">
        <blockquote class="blockquote">
            <p>
                Mistakes are happen
            </p>
        </blockquote>
        <figcaption class="blockquote-footer">
            Jan Angelovič, <cite title="Source Title">2021</cite>
        </figcaption>
    </figure>

    <figure class="text-center">
        <blockquote class="blockquote">
            <p>
                TBM#11 NMP unsuccessful exchange for W10 – in office every see ok and after exchange to but if production want to start non working corectli and we dont have time for tuning. We replece old SSD with W7 back.
            </p>
        </blockquote>
        <figcaption class="blockquote-footer">
            Petr Klíma, <cite title="Source Title">2021</cite>
        </figcaption>
    </figure>


    <figure class="text-center">
        <blockquote class="blockquote">
            <p>
                The database related to MES is managed by ICT and has been cleaned in 21 years.
            </p>
        </blockquote>
        <figcaption class="blockquote-footer">
            Lucas, <cite title="Source Title">2022</cite>
        </figcaption>
    </figure>

    <figure class="text-center">
        <blockquote class="blockquote">
            <p>
                Thank you for thinking that way. I can't do as much as I want to all of my team members at once whenever I have the opportunity, but I will do it for everyone equally for the effort I put in for the ICT team.
            </p>
        </blockquote>
        <figcaption class="blockquote-footer">
            Lucas, <cite title="Source Title">2022</cite>
        </figcaption>
    </figure>

    <figure class="text-center">
        <blockquote class="blockquote">
            <p>
                I understand us. But there are many times when they say what they say and say something else. let us understand
            </p>
        </blockquote>
        <figcaption class="blockquote-footer">
            Lucas, <cite title="Source Title">2022</cite>
        </figcaption>
    </figure>

    <figure class="text-center">
        <blockquote class="blockquote">
            <p>
                When you come to the office to work, be quiet so that you can focus on your work first.
            </p>
        </blockquote>
        <figcaption class="blockquote-footer">
            Lucas, <cite title="Source Title">2022</cite>
        </figcaption>
    </figure>


    <figure class="text-center">
        <blockquote class="blockquote">
            <p>
                "nešla" kamera, přetáhl jsem jí a vše ok
            </p>
        </blockquote>
        <figcaption class="blockquote-footer">
            Patrik Tůma, <cite title="Source Title">2023</cite>
        </figcaption>
    </figure>




</div>*@

NexenHub/Pages/Forbidden.cshtml
@page
@model NexenHub.Pages.ForbiddenModel
@{
}


<div class="container text-center">
    <div class="row">
        <div class="col ">
            <h2 class="text-danger">Access denied</h2>
        </div>
    </div>
</div>

NexenHub/Pages/Login.cshtml
@page
@model NexenHub.Pages.LoginModel
@{

}


<div class="container">
    <div class="row">

        <div class="col-lg">

        </div>

        <div class="col m-lg-3">

            <div class="bg-white p-3">

                <form method="post">

                    @if (!string.IsNullOrEmpty(Model.ErrorMsg)){

                    <div class="row">
                        <div class="col">
                            <div class="alert alert-danger" role="alert">
                                    @Model.ErrorMsg
                            </div>
                        </div>
                    </div>

                    }

                    <div class="row">
                        <div class="col">
                            <div class="input-group  mb-3">
                                <input type="text" class="form-control" placeholder="Employee ID" asp-for="Username">
                            </div>
                       
                        </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <div class="input-group mb-3">
                                <input type="password" class="form-control" placeholder="MES Password" asp-for="Password">
                            </div>
                         </div>
                    </div>

                    <div class="row">
                        <div class="col">
                            <div class="input-group">
                                <button type="submit" class="btn btn-primary w-100" asp-page-handler="Login">Sign in</button>
                            </div>
                        </div>
                    </div>

                </form>

            </div>

        </div>

        <div class="col-lg">

        </div>

    </div>
</div>

NexenHub/Pages/Logout.cshtml
@page "{returnPath?}"
@model NexenHub.Pages.LogoutModel
@{
}

<div class="container text-center">
    <div class="row">
        <div class="col ">
            <h2>Login out...</h2>
        </div>
    </div>
</div>

NexenHub/Pages/MachineReport.cshtml
@page "{eqarg?}/{startarg:datetime?}/{endarg:datetime?}"
@model NexenHub.Pages.MachineReportModel
@{
    ViewData["mainSelected"] = "machines";
}

<div class="container-fluid mb-3">

    <div class="row border-bottom border-2 pt-3 bg-filter">
        <div class="col">

            <div class="row">
                <div class="col">
                    <h4>Report generator</h4>
                </div>
            </div>

            <div class="row">
                
                <div class="col"></div>

                <div class="col-lg-6">
                    <form method="post">
                        <div class="input-group mb-3">

                            <span class="input-group-text">Machine</span>

                            <select class="form-control" asp-for="SelectedMachine">
                                <option value="" />
                        
                                @foreach (var Machine in Model.Machines)
                                {
                                    <option value="@Machine.EQ_ID">@Machine.EQ_ID - @Machine.Name</option>
                                }
                        
                            </select>

                            <span class="input-group-text">From</span>
                            <input type="text" id="myfrom" class="form-control" asp-for="DateFrom" data-provide="datepicker" data-date-end-date="0d">
                            <span class="input-group-text">To</span>
                            <input type="text" id="myTo" class="form-control" asp-for="DateTo" data-provide="datepicker" data-date-end-date="0d">
                            <button id="btnGenerate" type="submit" class="btn btn-primary" onclick="ShowSpinner();" asp-page-handler="generate">Generate report</button>
                            <button id="spinner" class="btn btn-primary" type="button" disabled style="visibility:collapse">
                                <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                                Loading...
                            </button>
                        </div>

                    </form>

                </div>

                <div class="col"></div>

            </div>

        </div>
    </div>

</div>

<div class="container">

     @if (Model.IsValid)
        {

        <div class="row mb-3">

            <div class="col">
                @await Component.InvokeAsync("MachineReportProd", Model.reportData)
            </div>

        </div>

        <div class="row">
            <div class="col">
                @await Component.InvokeAsync("MachineReportUsedMat", Model.reportUsedMaterial)
            </div>
        </div>

        }

</div>

<script type="text/javascript">

    $('#myfrom').datepicker({
        format: 'yyyy-mm-dd',
        weekStart: '1'
    });

    $('#myTo').datepicker({
        format: 'yyyy-mm-dd',
        weekStart: '1'
    });

    function ShowSpinner() {
        var spin = document.getElementById("spinner");
        var btn = document.getElementById("btnGenerate");

        spin.style.visibility = "visible";
        btn.style.visibility = "collapse";
    }

</script>

NexenHub/Pages/Rex.cshtml
@page
@model NexenHub.Pages.RexModel
@{
    ViewData["mainSelected"] = "rex";
}

<div class="container pt-3 bg-white">

    <div class="row">
        <div class="col text-center">
            <h1>Rex</h1>
            <div class="text-muted">@Html.Raw("v")@Model.RexVer.VersionDate.ToString("yyyy-MM-dd")</div>
        </div>
    </div>

    <div class="row g-3">
        <div class="col-lg-8">

            <h2>Požadavky</h2>
            <ul>
                <li>Android 8.0 a vyšší</li>
                <li>Telefon připojený k síti Nexen, schopný připojit se k tomuto webu.</li>
            </ul>

        <h2>Instalace</h2>
        <ol>
            <li>Stáhnout soubor rex.apk</li>
            <li>Stiskem souboru se pustí instalace.</li>
            <li>Odsouhlasit všechny hlášky, povolit všechno co telefon vyžaduje.</li>
            <li>Po prvním spuštění nemusí fungovat skenování čárového kódu, stačí restartovat.</li>
        </ol>

        <h2>Použití</h2>
        <ul>
            <li>Tlačítko "Zadat" - Manuální zadání čísla LOT / Vozíku.</li>
            <li>Tlačítko "Skenovat" - Přečte čárový / QR kód pomocí kamery. Ignoruje typy kódů, které nejsou součástí výroby.</li>
            <li>NFC - Po zapnutí NFC lze přiložit telefon na RFID čip vozíku.</li>
        </ul>

            @*<div class="w-100 d-none d-lg-block">
                <img src="~/images/rex/poklep.png" class="img-fluid" />
            </div>*@

        </div>

        <div class="col-lg-4">

                    <div class="flex-column">

                        <a href="@Url.Page("rex", "Download")" class="btn btn-primary m-1 w-100">Stáhnout</a>

                        <div class="w-100 d-none d-lg-block">
                            <img src="~/images/RexDownload.png" class="img-fluid"/>
                        </div>


                    </div>


        </div>

    </div>

</div>

NexenHub/Pages/Status.cshtml
@page "{proc?}"
@model NexenHub.Pages.StatusModel
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="refresh" content="30">
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/site.css" />
</head>

<body class="" style="background-color:#000000;">

        <div class="container-fluid mt-0 mt-md-3">
            
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 row-cols-xl-6 row-cols-xxl-12 g-2">
                @{ foreach (var status in Model.statuses)
                {
                    <div class="col">

                        @{string stl = "bg-dark";
                            string txtc = "text-light text-muted";
                            if (!string.IsNullOrEmpty(status.Downtime)) {
                                stl = "bg-warning";
                                txtc = "text-dark";
                            }
                        }

                        <div class="card h-100 @txtc @stl">
                            <div class="card-header text-center">
                                <h3> @status.Name </h3>
                            </div>
                            <div class="card-body text-center">
                                <h3>
                                    @{
                                    if (string.IsNullOrEmpty(status.Downtime))
                                        @status.Item_id
                                    else
                                        @status.Downtime
                                    }
                                </h3>
                            </div>
                        </div>

                    </div>
                }
                }
            </div>

        </div>


</body>
</html>